### ISSUE TITLE
Got "unexpected keyward argument 'output_layers' in the registration run

### ISSUE THREAD

**Issue by Zzhexiansun** [voxelmorph/voxelmorph#228]
TASK

Wanted to do a quick try of the voxelmorph  registration with my images and the trained models you provided.
I used the code your provded in the readme:
./scripts/tf/register.py --moving moving.nii.gz --fixed atlas.nii.gz --moved warped.nii.gz --model model.h5 --gpu 0

Questions:

I got the following error info:
Traceback (most recent call last):
  File "./scripts/tf/register.py", line 45, in <module>
    warp = vxm.networks.VxmDense.load(args.model).register(moving, fixed)
  File "/home/ibil/Downloads/ibil/envs/test/lib/python3.7/site-packages/voxelmorph/tf/modelio.py", line 103, in load
    model = cls(**config)
  File "/home/ibil/Downloads/ibil/envs/test/lib/python3.7/site-packages/voxelmorph/tf/modelio.py", line 22, in wrapper
    retval = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'output_layers'

Thank you in advance!

**Comment by adalca** [comment]
@ahoopes  should know best, but in the meanwhile can you confirm what version of tensorflow you are running?

**Comment by Zzhexiansun** [comment]
> @ahoopes should know best, but in the meanwhile can you confirm what version of tensorflow you are running?
Hi, just checked, tensorflow version = 1.14. 0
Any else information you need?
Btw, I was trying to use your model to register my images, will this issue due to my image?

**Comment by adalca** [comment]
most of the `master` branch requires tensorflow 2.0+, or at least we haven't worked with 1.14 on it. If you want to stick to 1.14, I recommend the `legacy` branch

**Comment by Zzhexiansun** [comment]
Thank you for the advice! I don't have any preference on the tensorflow version. Will try update it!

**Comment by Zzhexiansun** [comment]
Hmm, updated to tensorflow 2.2.0 but still got same error. Anything else I should check?

**Comment by ahoopes** [comment]
Where did you get `model.h5` from? Is it a `VxmDense` model? In the refactored master branch, the default model configurations have changed a bit, and probably won't be able to "smartly" load old model files. We will upload compatible TF and pytorch models soon.

**Comment by zhayanli** [comment]
Hello, I got the same error. Are the models uploading?

**Comment by adalca** [comment]
@ahoopes could we put an example model at a public address and link it here? It need not be on the git for now

**Comment by rueberger** [comment]
Same problem here with tf 2.4.0 and the unconditional model provided in the README. I get a similar traceback for the conditional model: `TypeError: __init__() got an unexpected keyword argument 'input_layers'`

**Comment by joshuacwnewton** [comment]
I encountered a similar error, this time with PyTorch instead of TensorFlow.

Example snippet of my script:

```python
os.environ['VXM_BACKEND'] = 'pytorch'
import voxelmorph as vxm

pt_first_model = vxm.networks.VxmDense(
    inshape=[192, 256, 320],
    int_steps=5,
    int_downsize=2,
    unet_half_res=True,
    nb_unet_features=([256, 256, 256, 256], [256, 256, 256, 256, 256, 256])
)
```

Error:

```
Traceback (most recent call last):
  File "C:\Users\Joshua\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5457.59\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\Joshua\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5457.59\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Joshua/repos/spinalcordtoolbox/test-pytorch-model-issue.py", line 10, in <module>
    nb_unet_features=([256, 256, 256, 256], [256, 256, 256, 256, 256, 256])
  File "C:\Users\Joshua\repos\spinalcordtoolbox\venv_sct\lib\site-packages\voxelmorph\torch\modelio.py", line 34, in wrapper
    return func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'unet_half_res'
```

In my case, the problem is that:

* My model loading script relied on newer VoxelMorph features (`unet_half_res`) introduced in a Feb 1, 2021 commit (https://github.com/voxelmorph/voxelmorph/commit/579a995492bddfe9ce38161e58cf260fc155c4fd). 
* However, I installed VoxelMorph from pip (`voxelmorph-0.1`), which was released on Sep 5, 2020.
* Version 0.1 does not have the `unet_half_res` argument.

To fix this issue:

* Don't install VoxelMorph from `pip`, or
* Limit your scripts to only using features included in `voxelmorph-0.1`, or
* Perhaps the VoxelMorph devs could release a new version on PyPI so that people who run `pip install voxelmorph` can access the newest changes to the model architectures. 

Thank you kindly! :)

**Comment by ahoopes** [comment]
Just an update on this - voxelmorph 0.2 has now been released on pypi. This version includes the unet_half_res argument from the development branch (among other changes 😃)
